import { ShieldIcon, LockIcon, CheckBadgeIcon } from "./icons/SecurityIcons";

const Footer = () => (
  <footer className="footer" role="contentinfo" aria-label="Site footer">
    <div className="footer-content">
      <div className="footer-security-badges" role="list" aria-label="Security certifications">
        <div className="security-badge" role="listitem">
          <ShieldIcon aria-hidden="true" />
          <span>SOC 2 Type II</span>
        </div>
        <div className="security-badge" role="listitem">
          <LockIcon aria-hidden="true" />
          <span>256-bit Encryption</span>
        </div>
        <div className="security-badge" role="listitem">
          <CheckBadgeIcon aria-hidden="true" />
          <span>GDPR Compliant</span>
        </div>
      </div>

      <div className="footer-data-handling">
        <h4>How We Handle Your Data</h4>
        <div className="data-handling-grid">
          <div className="data-handling-item">
            <strong>Audio Files</strong>
            <span>Processed in-memory only. Never stored or retained after analysis.</span>
          </div>
          <div className="data-handling-item">
            <strong>Analysis Results</strong>
            <span>Demo results are ephemeral. Enterprise clients control their data retention policies.</span>
          </div>
          <div className="data-handling-item">
            <strong>Third Parties</strong>
            <span>We never share your data with third parties. Your audio stays between you and our analysis engine.</span>
          </div>
        </div>
      </div>

      <p className="footer-copyright">
        &copy; {new Date().getFullYear()} <strong>Sonotheia</strong>, Inc. All rights reserved.
      </p>
      <p className="footer-tagline">
        Proprietary Detection Technology | Custom Enterprise Solutions
      </p>
      <div className="footer-legal">
        <p className="legal-disclaimer">
          <strong>Simulation Platform:</strong> Sonotheia AIETHIA is a forensic simulation and training environment.
          The data presented is generated by a physics engine for educational scenarios and does not represent
          analysis of real-world audio.
        </p>
        <p className="demo-disclaimer">
          <strong>Proprietary Technology:</strong> The "Scenario Engine", physics-based simulation models,
          and UI designs are proprietary assets of Sonotheia, Inc. Unauthorized commercial use of this
          simulation platform is prohibited.
        </p>
        <p className="no-warranty">
          TRAINING ONLY. NOT FOR PRODUCTION USE. SONOTHEIA MAKES NO
          CLAIMS REGARDING THE ACCURACY OF THESE SIMULATED METRICS FOR REAL-WORLD FRAUD DETECTION.
        </p>
      </div>
      <p className="footer-links">
        <a href="mailto:inquiries@sonotheia.ai" aria-label="Contact Sonotheia via email">
          Contact
        </a>
      </p>
    </div>
  </footer>
);

export default Footer;

