from fpdf import FPDF
from datetime import datetime
import os
from pathlib import Path
from typing import Dict, Any

from .models import SARContext

class PDFReport(FPDF):
    def header(self):
        # Header
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'SUSPICIOUS ACTIVITY REPORT (SAR)', new_x="LMARGIN", new_y="NEXT", align='C')
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 10, 'CONFIDENTIAL - FOR FINANCIAL INTELLIGENCE UNIT USE ONLY', new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(5)
        # Line break
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb} | Generated by Sonotheia Enhanced Platform', 0, 0, 'C')

class SARPDFGenerator:
    """Generates PDF reports for SAR contexts."""
    
    def __init__(self, output_dir: str = None):
        if output_dir:
            self.output_dir = Path(output_dir)
        else:
            self.output_dir = Path(__file__).parent.parent / "reports"
        
        self.output_dir.mkdir(exist_ok=True, parents=True)

    def generate(self, context: SARContext, narrative: str, report_id: str) -> str:
        """
        Generate a PDF SAR report.
        
        Args:
            context: The SAR context data
            narrative: The generated text narrative
            report_id: Unique ID for the report
            
        Returns:
            str: Absolute path to the generated PDF file
        """
        pdf = PDFReport()
        pdf.alias_nb_pages()
        pdf.add_page()
        
        # Section 1: Filing Information
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_fill_color(200, 220, 255)
        pdf.cell(0, 10, ' 1. FILING INFORMATION', border=1, new_x="LMARGIN", new_y="NEXT", align='L', fill=True)
        pdf.set_font('Helvetica', '', 10)
        pdf.ln(2)
        pdf.cell(95, 8, f"Report ID: {report_id}", new_x="RIGHT", new_y="TOP")
        pdf.cell(95, 8, f"generated Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(95, 8, f"Filing Institution: Incode Financial Services", new_x="RIGHT", new_y="TOP")
        pdf.cell(95, 8, f"Jurisdiction: United States (FinCEN)", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Section 2: Subject Information
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 10, ' 2. SUBJECT INFORMATION', border=1, new_x="LMARGIN", new_y="NEXT", align='L', fill=True)
        pdf.set_font('Helvetica', '', 10)
        pdf.ln(2)
        
        # Handle optional context fields safely
        customer_id = context.customer_id if hasattr(context, 'customer_id') else "Unknown"
        
        pdf.cell(95, 8, f"Customer ID: {customer_id}", new_x="RIGHT", new_y="TOP")
        pdf.cell(95, 8, f"Risk Level: {context.risk_intelligence.risk_level if context.risk_intelligence else 'UNKNOWN'}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Section 3: Suspicious Activity Description
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 10, ' 3. NARRATIVE & EVIDENCE', border=1, new_x="LMARGIN", new_y="NEXT", align='L', fill=True)
        pdf.set_font('Helvetica', '', 10)
        pdf.ln(2)
        
        # Write narrative
        # Multi-cell handles text wrapping
        pdf.multi_cell(0, 6, narrative)
        pdf.ln(10)

        # Section 4: Risk Intelligence
        if context.risk_intelligence:
            pdf.set_font('Helvetica', 'B', 12)
            pdf.cell(0, 10, ' 4. RISK INTELLIGENCE ANALYSIS', border=1, new_x="LMARGIN", new_y="NEXT", align='L', fill=True)
            pdf.set_font('Helvetica', '', 10)
            pdf.ln(2)
            
            risk = context.risk_intelligence
            pdf.cell(0, 8, f"Overall Risk Score: {risk.overall_risk_score:.2f}", new_x="LMARGIN", new_y="NEXT")
            
            if risk.geographic_risks:
                pdf.set_font('Helvetica', 'B', 10)
                pdf.cell(0, 8, "Geographic Risks:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font('Helvetica', '', 10)
                for geo in risk.geographic_risks:
                    pdf.cell(10, 8, "- ", new_x="RIGHT", new_y="TOP")
                    pdf.multi_cell(0, 8, geo)

            if risk.behavioral_anomalies:
                pdf.set_font('Helvetica', 'B', 10)
                pdf.cell(0, 8, "Behavioral Anomalies:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font('Helvetica', '', 10)
                for anomaly in risk.behavioral_anomalies:
                    pdf.cell(10, 8, "- ", new_x="RIGHT", new_y="TOP")
                    pdf.multi_cell(0, 8, anomaly)

        # Output
        filename = f"{report_id}.pdf"
        file_path = self.output_dir / filename
        pdf.output(str(file_path))
        
        return str(file_path)
