from fpdf import FPDF
import uuid
from datetime import datetime
import os
import random

# Ensure output directory exists
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(OUTPUT_DIR, exist_ok=True)

class SARPDF(FPDF):
    def header(self):
        # Header
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'SUSPICIOUS ACTIVITY REPORT (SAR)', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 10, 'CONFIDENTIAL - FOR FINANCIAL INTELLIGENCE UNIT USE ONLY', 0, 1, 'C')
        self.ln(5)
        # Line break
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb} | Generated by Sonotheia Enhanced Platform', 0, 0, 'C')

def generate_compliance_report():
    print("Generating Compliance Hero SAR Report...")
    
    # Simulating Data
    report_id = f"SAR-2025-{random.randint(10000, 99999)}"
    submission_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    subject_name = "John Doe (Simulated)"
    subject_id = "USER-8821-XJ"
    risk_score = 0.89
    incident_type = "Identity Theft / Synthetic Audio Injection"
    
    pdf = SARPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Section 1: Filing Information
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(0, 10, ' 1. FILING INFORMATION', 1, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.ln(2)
    pdf.cell(95, 8, f"Report ID: {report_id}", 0, 0)
    pdf.cell(95, 8, f"Submission Date: {submission_date}", 0, 1)
    pdf.cell(95, 8, "Filing Institution: Incode Financial Services", 0, 0)
    pdf.cell(95, 8, "Jurisdiction: United States (FinCEN)", 0, 1)
    pdf.ln(5)

    # Section 2: Subject Information
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, ' 2. SUBJECT INFORMATION', 1, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.ln(2)
    pdf.cell(95, 8, f"Full Name: {subject_name}", 0, 0)
    pdf.cell(95, 8, f"Internal ID: {subject_id}", 0, 1)
    pdf.cell(95, 8, "IP Address: 45.2.10.99 (Proxy Detected)", 0, 0)
    pdf.cell(95, 8, "Device ID: iPhone14,2 (Jailbroken)", 0, 1)
    pdf.ln(5)

    # Section 3: Suspicious Activity Description
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, ' 3. NARRATIVE & EVIDENCE', 1, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.ln(2)
    
    narrative = (
        f"On {submission_date.split(' ')[0]}, the Sonotheia Enhanced Platform detected a high-probability "
        f"attempt to bypass biometric authentication using synthetic media (Deepfake).\n\n"
        f"DETAILS OF SUSPICIOUS ACTIVITY:\n"
        f"During the onboarding session (ID: SESS-{random.randint(1000,9999)}), the user submitted "
        f"a voice verification sample that failed multiple liveness checks. "
        f"While the facial recognition (Incode) matched the provided ID document with 95% confidence, "
        f"the voice analysis (Sonotheia) indicated a 99.2% probability of synthetic generation.\n\n"
        f"TECHNICAL FORENSICS:\n"
        f"- Risk Score: {risk_score} (CRITICAL)\n"
        f"- Anomaly Detected: 'Vocoder Artifacts' in 4kHz-8kHz range.\n"
        f"- Phase Coherence: Non-biological patterns detected.\n"
        f"- Playback Injection: Probable virtual microphone driver used.\n\n"
        f"ACTION TAKEN:\n"
        f"Session was automatically terminated. Account creation blocked. "
        f"Device signature added to global blocklist."
    )
    
    pdf.multi_cell(0, 6, narrative)
    pdf.ln(10)

    # Section 4: Visual Evidence (Mock)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, ' 4. DIGITAL FORENSICS ATTACHMENT', 1, 1, 'L', fill=True)
    pdf.ln(5)
    
    # Draw a mock graph/spectrogram
    pdf.set_font('Courier', '', 8)
    pdf.cell(0, 5, "[ SPECTROGRAM ANALYSIS LOG ]", 0, 1)
    pdf.cell(0, 5, "0.0s  |  ||||||||||  Normal Energy", 0, 1)
    pdf.cell(0, 5, "0.5s  |  ||||||||||  Normal Energy", 0, 1)
    pdf.cell(0, 5, "1.0s  |  ||||||||||  Normal Energy", 0, 1)
    pdf.cell(0, 5, "1.5s  |  ##########  <-- SYNTHETIC ARTIFACT DETECTED (High Freq)", 0, 1)
    pdf.cell(0, 5, "2.0s  |  ##########  <-- PHASE DISCONTINUITY", 0, 1)
    pdf.cell(0, 5, "2.5s  |  ||||||||||  Normal Energy", 0, 1)
    
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 10)
    pdf.cell(0, 10, f"Signed Electronically: Sonotheia Compliance Module v2.4", 0, 1, 'R')

    # Output
    filename = f"SAR_{report_id}.pdf"
    file_path = os.path.join(OUTPUT_DIR, filename)
    pdf.output(file_path)
    
    print(f"SUCCESS: Compliance Action complete.")
    print(f"Generated Audit Report: {file_path}")
    return file_path

if __name__ == "__main__":
    generate_compliance_report()
